project_id = "nzckeknlyzzxxqeczkzh"

[functions.extract-brand-colors]
verify_jwt = false

[functions.chat-ai]
verify_jwt = false

[functions.track-page-analytics]
verify_jwt = false

[functions.send-agent-invitation]
verify_jwt = false

[functions.extract-visitor-info]
verify_jwt = false

[functions.slack-oauth-callback]
verify_jwt = false

[functions.slack-oauth-start]
verify_jwt = false

[functions.get-visitor-location]
verify_jwt = false

[functions.update-visitor]
verify_jwt = false

[functions.salesforce-export-leads]
verify_jwt = false

[functions.get-property-ai-agents]
verify_jwt = false
